@startuml
' =========================
' Diagrama de Objetos
' =========================
hide empty members
hide circle
skinparam objectFontSize 12

object Planta_Menos3 {
  numero = -3
  esperando = [Persona_Alice]
  enPlanta = []
}
object Persona_Alice {
  destino = 0
  tiempoRestante = 0
  quiereSalir = false
}
object Llamada_Alice {
  origen = -3
  persona = Persona_Alice
}
object Ascensor_A1 {
  id = "A1"
  plantaActual = -3
  personas = []
  llamadas = [Llamada_Alice]
}

Planta_Menos3 --> Persona_Alice
Persona_Alice --> Llamada_Alice
Llamada_Alice --> Ascensor_A1
@enduml
