@startuml
' Diagrama de Estados: Planta
hide empty description

[*] --> Recibiendo

Recibiendo --> GenerandoLlamada : persona llega a la planta
GenerandoLlamada --> EsperandoAscensor : llamada procesada
EsperandoAscensor --> Abordando : ascensor llega y recoge personas
Abordando --> Recibiendo : última persona abordó
@enduml
