@startuml
' =========================
' Diagrama de Estados (Persona)
' =========================
hide empty description

[*] --> Creada : inicio
Creada --> Esperando : personaEsperaAscensor
Esperando --> EnAscensor : recoger
EnAscensor --> SeleccionandoPlanta : elige planta
SeleccionandoPlanta --> EnMovimiento : mover
EnMovimiento --> EnPlanta : bajar
EnPlanta --> SaliendoUniversidad : jornada completa
SaliendoUniversidad --> FueraUniversidad : salida edificio
FueraUniversidad --> [*] : fin

@enduml
