@startuml
' Diagrama de Estados: Ascensor
hide empty description

[*] --> Esperando

Esperando --> Cargando : solicitud en planta actual
Cargando --> Moviéndose : puertas cerradas y hay tareas pendientes
Moviéndose --> Descargando : llega a la planta destino
Descargando --> Esperando : empieza e ciclo

Moviéndose --> Moviéndose : sigue moviéndose
Cargando --> Cargando : sigue cargando personas
Descargando --> Descargando : sigue descargando personas
Descargando --> [*]: fin de ciclo
@enduml
