@startuml
' Diagrama de Estados: Planta
hide empty description

[*] --> Recibiendo

Recibiendo --> GenerandoLlamada : persona llega a la planta
GenerandoLlamada --> EsperandoAscensor : llamada procesada
EsperandoAscensor --> Entrando : ascensor llega y recoge personas
Entrando --> Recibiendo : última persona entro al ascensor
Entrando -->  [*]

@enduml

